#!/usr/bin/env python3

import re
import sys
from urllib.request import urlopen

# https://ptr.wowhead.com/items?filter=107:195:216;0:2:1;innkeeper:0:0

def scrape(path, pattern):
	page = urlopen(f'https://ptr.wowhead.com/{path}')
	html = page.read().decode('utf-8')
	return re.findall(pattern, html)

hearthstoneIDs = []

sys.stderr.write('Scraping wowhead for itemIDs...\n')

itemIDs = scrape('items?filter=107:195:216;0:2:1;innkeeper:0:0', r'"(\d+)":{"name_enus')

if itemIDs == None or len(itemIDs) == 0:
	sys.stderr.write('No itemIDs found\n')
	sys.exit(1)

for itemID in itemIDs:
	hearthstoneIDs.append(int(itemID))

print('local HEARTHSTONE_TOYS = {')
print('\t-- generated by get_hearthstone_items.py')

for itemID in sorted(hearthstoneIDs):
	print(f'\t{itemID},')

print('}')

sys.stderr.write('Done\n')
