std = 'lua51'

quiet = 1 -- suppress report output for files without warnings

-- see https://luacheck.readthedocs.io/en/stable/warnings.html#list-of-warnings
-- and https://luacheck.readthedocs.io/en/stable/cli.html#patterns
ignore = {
	'212/self', -- unused argument self
	'212/event', -- unused argument event
	'212/unit', -- unused argument unit
	'212/element', -- unused argument element
	'312/event', -- unused value of argument event
	'312/unit', -- unused value of argument unit
	'431', -- shadowing an upvalue
	'631', -- line is too long
}

exclude_files = {}

globals = {
	-- FrameXML objects we mutate (taint city)
	'ChatTypeInfo',
	'StaticPopupDialogs',
	'MainMenuMicroButton_ShowAlert',

	-- globals we expose
	'GetMinimapShape',

	-- savedvariables
	'InomenaPlayed',
	'OPie_SavedData', -- we mutate OPie's savedvariables
}

read_globals = {
	-- stdlib
	string = {
		fields = {
			'split',
		},
	},

	-- FrameXML frames and widgets
	'BuffFrame',
	'CalendarFrame',
	'ChatFrame1EditBox',
	'ChatFrame1EditBoxHeader',
	'CooldownViewerSettings',
	'CreateFrame',
	'DeveloperConsole',
	'DressUpFrame',
	'EventToastManagerFrame',
	'GameTooltip',
	'GameTooltipStatusBar',
	'HybridMinimap',
	'MainActionBar',
	'MerchantFrame',
	'Minimap',
	'MinimapCluster',
	'OverlayPlayerCastingBarFrame',
	'PetActionBar',
	'PlayerSpellsFrame',
	'QueueStatusButton',
	'SendMailMailButton',
	'SendMailMoneyCopper',
	'SendMailMoneyGold',
	'SendMailMoneySilver',
	'SendMailNameEditBox',
	'SendMailSubjectEditBox',
	'ShoppingTooltip1',
	'ShoppingTooltip2',
	'UIErrorsFrame',
	'UIParent',
	'WeeklyRewardsFrame',
	'WorldMapFrame',
	'WorldMapFrameTitleText',

	-- FrameXML constants
	'CurveConstants',
	'BASE_MOVEMENT_SPEED',
	'COPPER_PER_GOLD',
	'COPPER_PER_SILVER',
	'DEFAULT_CHAT_FRAME',
	'FACTION_BAR_COLORS',
	'NUM_ACTIONBAR_BUTTONS',
	'NUM_CHAT_WINDOWS',
	'PAPERDOLL_STATCATEGORIES',
	'RANGE_INDICATOR',
	'SILVER_PER_GOLD',

	-- FrameXML mixins
	'DressUpCustomSetDetailsSlotMixin',
	'MinimapMixin',
	'TextureLoadingGroupMixin',

	-- FrameXML misc objects
	'ChatTypeInfo',
	'CVarCallbackRegistry',
	'Menu',
	'PowerBarColor',
	'SlashCmdList',
	'TooltipComparisonManager',
	'CHAT_FRAMES',
	'INVENTORY_ALERT_STATUS_SLOTS',
	'SELECTED_CHAT_FRAME',

	-- FrameXML utils
	'ActionButtonUtil',
	'AnchorUtil',
	'ChatFrameUtil',
	'MenuUtil',
	'TooltipDataProcessor',

	-- FrameXML functions
	'CreateAnchor',
	'CreateAtlasMarkup',
	'CreateColor',
	'FormatLargeNumber',
	'GameTooltip_Hide',
	'GameTooltip_SetDefaultAnchor',
	'GenerateClosure',
	'GetMoneyString',
	'HideUIPanel',
	'RegisterAttributeDriver',
	'RegisterStateDriver',
	'SecondsToTime',
	'ShowUIPanel',
	'WrapTextInColorCode',
	'nop',

	-- SharedXML constants
	'SOUNDKIT',

	-- GlobalStrings
	'CHAT_GUILD_INVITE_SEND',
	'COOLDOWN_REMAINING',
	'DASH_WITH_TEXT',
	'ERR_MAIL_INVALID_ATTACHMENT_SLOT',
	'EVENT_TOAST_EXPANDED_DESCRIPTION',
	'HAVE_MAIL',
	'HEADER_COLON',
	'HOUSING_DASHBOARD_RETURN',
	'HOUSING_DASHBOARD_TELEPORT_BUTTON_TEXT',
	'MINIMAP_TRACKING_MAILBOX',
	'MINIMAP_TRACKING_REPAIR',
	'MONEY',
	'PROFESSIONS_CRAFTING_ORDERS_PAGE_NAME',
	'SPELL_CAST_TIME_SEC',
	'SPELL_RECAST_TIME_MIN',
	'TIME_DAYHOURMINUTESECOND',
	'UNAVAILABLE',
	'UNKNOWN',
	'WEEKLY_REWARDS_COMPLETED_ENCOUNTER',

	-- namespaces
	'C_ActionBar',
	'C_AddOns',
	'C_ChallengeMode',
	'C_ClassColor',
	'C_ClassTalents',
	'C_ColorUtil',
	'C_CraftingOrders',
	'C_CurveUtil',
	'C_CVar',
	'C_DateAndTime',
	'C_DurationUtil',
	'C_GossipInfo',
	'C_GuildInfo',
	'C_Housing',
	'C_IncomingSummon',
	'C_Item',
	'C_Map',
	'C_MerchantFrame',
	'C_Minimap',
	'C_MountJournal',
	'C_PlayerInfo',
	'C_QuestLog',
	'C_Sound',
	'C_SpecializationInfo',
	'C_Spell',
	'C_SpellBook',
	'C_StringUtil',
	'C_Timer',
	'C_Traits',
	'C_UI',
	'C_UnitAuras',
	'Enum',

	-- API
	'AbbreviateNumbers',
	'CanEjectPassengerFromSeat',
	'CanGuildBankRepair',
	'CanMerchantRepair',
	'ConfirmLootSlot',
	'CursorHasItem',
	'EjectPassengerFromSeat',
	'EquipPendingItem',
	'GetAchievementInfo',
	'GetActionInfo',
	'GetBattlefieldStatus',
	'GetBindingKey',
	'GetClassInfo',
	'GetGuildBankMoney',
	'GetGuildInfo',
	'GetGuildRosterInfo',
	'GetInstanceInfo',
	'GetInventoryAlertStatus',
	'GetInventoryItemTexture',
	'GetLatestThreeSenders',
	'GetMoney',
	'GetNumClasses',
	'GetNumGroupMembers',
	'GetNumGuildMembers',
	'GetNumSpecializations',
	'GetPetActionInfo',
	'GetPhysicalScreenSize',
	'GetPlayerInfoByGUID',
	'GetRaidRosterInfo',
	'GetRealmName',
	'GetRepairAllCost',
	'GetRuneCooldown',
	'GetServerTime',
	'GetShapeshiftFormID',
	'GetSpecializationInfoForClassID',
	'GetTime',
	'GetUnitName',
	'GetWeaponEnchantInfo',
	'HasFullControl',
	'HasNewMail',
	'InCombatLockdown',
	'IsAltKeyDown',
	'IsControlKeyDown',
	'IsEncounterInProgress',
	'IsGUIDInGroup',
	'IsInInstance',
	'IsInRaid',
	'IsResting',
	'IsShiftKeyDown',
	'Mixin',
	'PlaySound',
	'RepairAllItems',
	'RequestTimePlayed',
	'SellCursorItem',
	'SetOverrideBinding',
	'TaxiRequestEarlyLanding',
	'UnitAffectingCombat',
	'UnitCanAttack',
	'UnitClass',
	'UnitClassBase',
	'UnitClassification',
	'UnitCreatureID',
	'UnitEffectiveLevel',
	'UnitExists',
	'UnitFactionGroup',
	'UnitGetTotalAbsorbs',
	'UnitGroupRolesAssigned',
	'UnitGUID',
	'UnitHasIncomingResurrection',
	'UnitHasVehicleUI',
	'UnitHealth',
	'UnitHealthMissing',
	'UnitHealthPercent',
	'UnitInVehicle',
	'UnitIsAFK',
	'UnitIsCharmed',
	'UnitIsConnected',
	'UnitIsDead',
	'UnitIsDeadOrGhost',
	'UnitIsEnemy',
	'UnitIsFriend',
	'UnitIsGameObject',
	'UnitIsGhost',
	'UnitIsGroupLeader',
	'UnitIsOtherPlayersPet',
	'UnitIsPlayer',
	'UnitIsPossessed',
	'UnitIsPVP',
	'UnitIsTapDenied',
	'UnitIsUnit',
	'UnitLevel',
	'UnitName',
	'UnitNameFromGUID',
	'UnitNameplateShowsWidgetsOnly',
	'UnitNameUnmodified',
	'UnitOnTaxi',
	'UnitPower',
	'UnitPowerPercent',
	'UnitPowerType',
	'UnitReaction',
	'UnitSpellTargetClass',
	'UnitSpellTargetName',
	'UnitThreatSituation',
	'UnitTokenFromGUID',
	'UnitTreatAsPlayerForDisplay',
	'UnitVehicleSeatCount',
	'hooksecurefunc',

	-- misc globals
	'NUM_LE_FRAME_TUTORIALS',

	-- luacheck gets confused about oUF's tag environment
	'_TAGS',
	'Hex',

	-- exposed from other addons
	'BugGrabber',
	'LibStub',
	'NotGameTooltip1', -- OPie's custom tooltip
	'OPie',
	'Syndicator',
	'TomTomTooltip',
}
