std = 'lua51'

quiet = 1 -- suppress report output for files without warnings

-- see https://luacheck.readthedocs.io/en/stable/warnings.html#list-of-warnings
-- and https://luacheck.readthedocs.io/en/stable/cli.html#patterns
ignore = {
	'212/self', -- unused argument self
	'212/event', -- unused argument event
	'212/unit', -- unused argument unit
	'212/element', -- unused argument element
	'312/event', -- unused value of argument event
	'312/unit', -- unused value of argument unit
	'431', -- shadowing an upvalue
	'631', -- line is too long
}

exclude_files = {}

globals = {
	-- FrameXML objects we mutate (taint city)
	'ChatTypeInfo',
	'StaticPopupDialogs',
	'MainMenuMicroButton_ShowAlert',

	-- globals we expose
	'GetMinimapShape',

	-- savedvariables
	'InomenaPlayed',
	'OPie_SavedData', -- we mutate OPie's savedvariables
}

read_globals = {
	-- stdlib
	string = {
		fields = {
			'split',
		},
	},
	bit = {
		fields = {
			'band',
		},
	},

	-- FrameXML frames and widgets
	'AuctionHouseFrame',
	'BuffFrame',
	'CalendarFrame',
	'CharacterFrame',
	'CharacterLevelText',
	'ChatFrame1EditBox',
	'ChatFrame1EditBoxHeader',
	'CooldownViewerSettings',
	'CovenantRenownFrame',
	'CreateFrame',
	'DeveloperConsole',
	'DressUpFrame',
	'DressUpFrameResetButton',
	'EncounterJournal',
	'EventToastManagerFrame',
	'ExpansionLandingPage',
	'ExpansionLandingPageMinimapButton',
	'GameTooltip',
	'GameTooltipDefaultContainer',
	'GameTooltipStatusBar',
	'GarrisonLandingPage',
	'GarrisonShipyardFrame',
	'HybridMinimap',
	'LFDRoleCheckPopupAcceptButton',
	'MainActionBar',
	'MajorFactionRenownFrame',
	'MerchantFrame',
	'Minimap',
	'MinimapCluster',
	'OverlayPlayerCastingBarFrame',
	'PaperDollFrame',
	'PaperDollSidebarTab3',
	'PetActionBar',
	'PlayerSpellsFrame',
	'ProfessionsFrame',
	'QueueStatusButton',
	'SendMailMailButton',
	'SendMailMoneyCopper',
	'SendMailMoneyGold',
	'SendMailMoneySilver',
	'SendMailNameEditBox',
	'SendMailSubjectEditBox',
	'ShoppingTooltip1',
	'ShoppingTooltip2',
	'UIErrorsFrame',
	'UIParent',
	'WeeklyRewardsFrame',
	'WorldMapFrame',
	'WorldMapFrameTitleText',

	-- FrameXML constants
	'CurveConstants',
	'BASE_MOVEMENT_SPEED',
	'BNET_CLIENT_WOW',
	'CONTAINER_BAG_OFFSET',
	'COPPER_PER_GOLD',
	'COPPER_PER_SILVER',
	'DEFAULT_CHAT_FRAME',
	'FACTION_BAR_COLORS',
	'NUM_ACTIONBAR_BUTTONS',
	'PAPERDOLL_STATCATEGORIES',
	'PLAYER_FACTION_COLOR_ALLIANCE',
	'PLAYER_FACTION_COLOR_HORDE',
	'RANGE_INDICATOR',
	'SILVER_PER_GOLD',
	'WOW_PROJECT_ID',

	-- FrameXML mixins
	'DressUpCustomSetDetailsSlotMixin',
	'MinimapMixin',

	-- FrameXML misc objects
	'CVarCallbackRegistry',
	'Menu',
	'NamePlateFriendlyFrameOptions',
	'PaperDollSidebarTabs',
	'PowerBarColor',
	'SlashCmdList',
	'TooltipComparisonManager',
	'CHAT_FRAMES',
	'INVENTORY_ALERT_STATUS_SLOTS',
	'SELECTED_CHAT_FRAME',
	'WHITE_FONT_COLOR',

	-- FrameXML utils
	'ActionButtonUtil',
	'AnchorUtil',
	'ChatFrameUtil',
	'Item',
	'ItemLocation',
	'MenuUtil',
	'TooltipDataProcessor',

	-- FrameXML functions
	'CooldownFrame_Set',
	'CreateAnchor',
	'CreateAtlasMarkup',
	'CreateColor',
	'FCF_Close',
	'FCF_GetChatWindowInfo',
	'FCF_OpenNewWindow',
	'FCF_ResetChatWindows',
	'FCF_SelectDockFrame',
	'FCF_SetChatWindowFontSize',
	'FCF_SetWindowAlpha',
	'FCF_SetWindowColor',
	'FormatLargeNumber',
	'GameTooltip_Hide',
	'GameTooltip_SetDefaultAnchor',
	'GenerateClosure',
	'GenerateFlatClosure',
	'GetMoneyString',
	'HideUIPanel',
	'RegisterAttributeDriver',
	'RegisterStateDriver',
	'SecondsToTime',
	'ShowGarrisonLandingPage',
	'ShowUIPanel',
	'StaticPopup_Hide',
	'StaticPopup_Visible',
	'WrapTextInColorCode',
	'nop',

	-- SharedXML constants
	'SOUNDKIT',

	-- GlobalStrings
	'AZERITE_ISLANDS_XP_GAIN',
	'AZERITE_XP_GAIN',
	'BNET_CLIENT_APP',
	'BNET_CLIENT_APP',
	'CHAT_FLAG_AFK',
	'CHAT_FLAG_DND',
	'CHAT_GUILD_INVITE_SEND',
	'COOLDOWN_REMAINING',
	'CURRENCY',
	'DASH_WITH_TEXT',
	'DURABILITY',
	'ENCOUNTER_JOURNAL_ITEM',
	'ERR_LEARN_ABILITY_S',
	'ERR_LEARN_PASSIVE_S',
	'ERR_LEARN_SPELL_S',
	'ERR_MAIL_INVALID_ATTACHMENT_SLOT',
	'ERR_SPELL_UNLEARNED_S',
	'EVENT_TOAST_EXPANDED_DESCRIPTION',
	'EXPANSION_NAME5',
	'EXPANSION_NAME6',
	'EXPANSION_NAME7',
	'EXPANSION_NAME8',
	'GARRISON_LANDING_PAGE_TITLE',
	'GARRISON_TYPE_8_0_LANDING_PAGE_TITLE',
	'GARRISON_TYPE_9_0_LANDING_PAGE_TITLE',
	'HAVE_MAIL',
	'HEADER_COLON',
	'HOUSING_DASHBOARD_RETURN',
	'HOUSING_DASHBOARD_TELEPORT_BUTTON_TEXT',
	'ID',
	'LEADER',
	'MACRO',
	'MINIMAP_TRACKING_MAILBOX',
	'MINIMAP_TRACKING_REPAIR',
	'MONEY',
	'MOUNT',
	'NAME',
	'NPEV2_CHAT_GUIDE_FRAME_TITLE_STOP_GUIDING',
	'ORDER_HALL_LANDING_PAGE_TITLE',
	'PROFESSIONS_CRAFTING_ORDERS_PAGE_NAME',
	'PROF_CRAFTING_ORDER_TYPE_NPC',
	'RAID_WARNING',
	'SELL_PRICE',
	'SPELL_CAST_TIME_SEC',
	'SPELL_RECAST_TIME_MIN',
	'SPELL_TARGET_CENTER_CASTER',
	'STAT_CATEGORY_SPELL',
	'TIME_DAYHOURMINUTESECOND',
	'TRANSMOG_SOURCE_2',
	'UNAVAILABLE',
	'UNKNOWN',
	'WEEKLY_REWARDS_COMPLETED_ENCOUNTER',

	-- namespaces
	'C_ActionBar',
	'C_AddOns',
	'C_AuctionHouse',
	'C_BattleNet',
	'C_CVar',
	'C_ChallengeMode',
	'C_ChatInfo',
	'C_ClassColor',
	'C_ClassTalents',
	'C_ColorUtil',
	'C_Container',
	'C_ContentTracking',
	'C_Covenants',
	'C_CraftingOrders',
	'C_CreatureInfo',
	'C_CurveUtil',
	'C_DateAndTime',
	'C_DurationUtil',
	'C_EquipmentSet',
	'C_FriendList',
	'C_Garrison',
	'C_GossipInfo',
	'C_GuildInfo',
	'C_Housing',
	'C_IncomingSummon',
	'C_Item',
	'C_Macro',
	'C_Map',
	'C_MerchantFrame',
	'C_Minimap',
	'C_MountJournal',
	'C_PartyInfo',
	'C_PerksActivities',
	'C_PetJournal',
	'C_PlayerInfo',
	'C_QuestLog',
	'C_Secrets',
	'C_Sound',
	'C_SpecializationInfo',
	'C_Spell',
	'C_SpellBook',
	'C_StringUtil',
	'C_Timer',
	'C_TradeSkillUI',
	'C_Traits',
	'C_UI',
	'C_UnitAuras',
	'Constants',
	'Enum',

	-- API
	'AbbreviateNumbers',
	'AcceptGroup',
	'AutoEquipCursorItem',
	'CanEjectPassengerFromSeat',
	'CanGuildBankRepair',
	'CanMerchantRepair',
	'CancelShapeshiftForm',
	'ClearCursor',
	'ConfirmLootSlot',
	'CursorHasItem',
	'EjectPassengerFromSeat',
	'EnumerateFrames',
	'EquipPendingItem',
	'GetAchievementInfo',
	'GetActionInfo',
	'GetBattlefieldStatus',
	'GetBindingKey',
	'GetClassInfo',
	'GetGuildBankMoney',
	'GetGuildInfo',
	'GetGuildRosterInfo',
	'GetInstanceInfo',
	'GetInventoryAlertStatus',
	'GetInventoryItemDurability',
	'GetInventoryItemID',
	'GetInventoryItemTexture',
	'GetLatestThreeSenders',
	'GetLootSlotInfo',
	'GetLootSlotType',
	'GetMacroItem',
	'GetMaxLevelForPlayerExpansion',
	'GetMoney',
	'GetNextPendingInviteConfirmation',
	'GetNumClasses',
	'GetNumGroupMembers',
	'GetNumGuildMembers',
	'GetNumLootItems',
	'GetNumSpecializations',
	'GetPetActionInfo',
	'GetPhysicalScreenSize',
	'GetPlayerInfoByGUID',
	'GetRaidRosterInfo',
	'GetRealmName',
	'GetRepairAllCost',
	'GetRuneCooldown',
	'GetServerTime',
	'GetShapeshiftFormID',
	'GetSpecializationInfoForClassID',
	'GetTime',
	'GetUnitName',
	'GetWeaponEnchantInfo',
	'HasFullControl',
	'HasNewMail',
	'InCombatLockdown',
	'IsAltKeyDown',
	'IsControlKeyDown',
	'IsEncounterInProgress',
	'IsFlyableArea',
	'IsGUIDInGroup',
	'IsInInstance',
	'IsInRaid',
	'IsResting',
	'IsShiftKeyDown',
	'IsSubmerged',
	'IsTestBuild',
	'LootSlot',
	'Mixin',
	'PickupInventoryItem',
	'PlaySound',
	'PlayerHasToy',
	'PutItemInBackpack',
	'PutItemInBag',
	'RepairAllItems',
	'RequestTimePlayed',
	'RespondToInviteConfirmation',
	'SellCursorItem',
	'SetOverrideBinding',
	'TaxiRequestEarlyLanding',
	'UnitAffectingCombat',
	'UnitCanAttack',
	'UnitClass',
	'UnitClassBase',
	'UnitClassFromGUID',
	'UnitClassification',
	'UnitCreatureID',
	'UnitEffectiveLevel',
	'UnitExists',
	'UnitFactionGroup',
	'UnitGUID',
	'UnitGetTotalAbsorbs',
	'UnitGroupRolesAssigned',
	'UnitHasIncomingResurrection',
	'UnitHasVehicleUI',
	'UnitHealth',
	'UnitHealthMax',
	'UnitHealthMissing',
	'UnitHealthPercent',
	'UnitInVehicle',
	'UnitIsAFK',
	'UnitIsCharmed',
	'UnitIsConnected',
	'UnitIsDead',
	'UnitIsDeadOrGhost',
	'UnitIsEnemy',
	'UnitIsFriend',
	'UnitIsGameObject',
	'UnitIsGhost',
	'UnitIsGroupLeader',
	'UnitIsMinion',
	'UnitIsOtherPlayersPet',
	'UnitIsPVP',
	'UnitIsPlayer',
	'UnitIsPossessed',
	'UnitIsTapDenied',
	'UnitIsUnit',
	'UnitLevel',
	'UnitName',
	'UnitNameFromGUID',
	'UnitNameUnmodified',
	'UnitNameplateShowsWidgetsOnly',
	'UnitOnTaxi',
	'UnitPower',
	'UnitPowerPercent',
	'UnitPowerType',
	'UnitRace',
	'UnitReaction',
	'UnitSelectionColor',
	'UnitSpellTargetClass',
	'UnitSpellTargetName',
	'UnitThreatSituation',
	'UnitTokenFromGUID',
	'UnitTreatAsPlayerForDisplay',
	'UnitVehicleSeatCount',
	'hooksecurefunc',
	'issecretvalue',

	-- misc globals
	'LE_EXPANSION_MIDNIGHT',
	'NUM_LE_FRAME_TUTORIALS',

	-- luacheck gets confused about oUF's tag environment
	'_TAGS',
	'_COLORS',
	'Hex',

	-- exposed from other addons
	'BugGrabber',
	'LibStub',
	'OPie',
	'Syndicator',
	'TomTomTooltip',
}
