local gear = cargoShip('Broker_Equipment', {noText = true})
gear:SetPoint('BOTTOMRIGHT', Minimap, -1, 1)
gear:HookScript('OnLeave', function() gear:SetAlpha(0) end)
gear:HookScript('OnEnter', function() gear:SetAlpha(1) end)
gear:SetWidth(gear:GetHeight())
gear:SetAlpha(0)
