local _, Inomena = ...

Inomena.Register('PLAYER_ENTERING_WORLD', function()
	for key, value in pairs({
		autoDismountFlying = 1,
		lootUnderMouse = 0,
		autoLootDefault = 1,
		showClock = 0,
		showLootSpam = 0,
		showItemLevel = 1,
		advancedWorldMap = 1,
		profanityFilter = 0,
		chatBubblesParty = 0,
		removeChatDelay = 1,
		guildRecruitmentChannel = 0,
		UnitNamePlayerGuild = 0,
		UnitNamePlayerPVPTitle = 0,
		UnitNameFriendlyPetName = 0,
		UnitNameEnemyPetName = 0,
		nameplateAllowOverlap = 0,
		nameplateShowFriendlyPets = 0,
		nameplateShowFriendlyGuardians = 0,
		nameplateShowFriendlyTotems = 0,
		nameplateShowEnemyPets = 0,
		nameplateShowEnemyGuardians = 0,
		nameplateShowEnemyTotems = 0,
		enableCombatText = 0,
		showArenaEnemyFrames = 0,
		cameraWaterCollision = 0,
		cameraSmoothStyle = 0,
		cameraDistanceMaxFactor = 4,
		cameraDistanceMax = 20,
		previewTalents = 1,
		showTutorials = 0,
		showGameTips = 0,
		showNewbieTips = 0,
		scriptErrors = 1,
		showToastOnline = 0,
		showToastOffline = 0,
		showToastBroadcast = 0,
		showToastWindow = 0,
		chatStyle = 'classic',

		processAffinityMask = 15,
		gxTripleBuffer = 1,
		textureFilteringMode = 5,
		componentTextureLevel = 9,
		shadowLevel = 0,
		farclip = 2000,
		groundEffectDensity = 256,
		groundEffectDist = 140,
		environmentDetail = 1.5,
		extShadowQuality = 5,
		weatherDensity = 0,
		SkyCloudLOD = 3,
		ffxGlow = 0,
		ffxDeath = 0,
		useUiScale = 1,
		UIScale = 768/1200,

		Sound_EnableSFX = 0,
		Sound_EnableMusic = 0,
		Sound_EnableAmbience = 0,
		Sound_EnableDSPEffects = 0,
		Sound_EnableSoundWhenGameIsInBG = 1,

		synchronizeSettings = 0,
		screenshotQuality = 10,
		taintLog = 1,
	}) do
		SetCVar(key, value)
	end
end)
