local _, addon = ...

local ENCHANT_IDS = {
	-- generated by get_enchant_ids.py
	-- enchantID = spellID
	[13] = 2829, -- Sharpen Blade II
	[14] = 2830, -- Sharpen Blade III
	[19] = 3112, -- Enhance Blunt Weapon
	[20] = 3113, -- Enhance Blunt Weapon II
	[21] = 3114, -- Enhance Blunt Weapon III
	[25] = 3594, -- Shadow Oil
	[26] = 3595, -- Frost Oil
	[40] = 2828, -- Sharpen Blade
	[263] = 8087, -- Shiny Bauble
	[264] = 8088, -- Nightcrawlers
	[265] = 9092, -- Flesh Eating Worm
	[266] = 45731, -- Sharpened Fish Hook
	[483] = 9900, -- Sharpen Blade IV
	[484] = 9903, -- Enhance Blunt Weapon IV
	[1643] = 16138, -- Sharpen Blade V
	[1703] = 16622, -- Enhance Blunt Weapon V
	[2506] = 22756, -- Elemental Sharpening Stone
	[2611] = 345914, -- Windfury Weapon
	[2623] = 25117, -- Minor Wizard Oil
	[2624] = 25118, -- Minor Mana Oil
	[2625] = 25120, -- Lesser Mana Oil
	[2626] = 25119, -- Lesser Wizard Oil
	[2627] = 25121, -- Wizard Oil
	[2628] = 25122, -- Brilliant Wizard Oil
	[2629] = 25123, -- Brilliant Mana Oil
	[2677] = 28013, -- Superior Mana Oil
	[2678] = 28017, -- Superior Wizard Oil
	[2712] = 29452, -- Sharpen Blade
	[2713] = 29453, -- Sharpen Blade
	[2718] = 32274, -- Lesser Rune of Warding
	[2791] = 32282, -- Greater Rune of Warding
	[2795] = 32426, -- Comfortable Insoles
	[2954] = 34339, -- Enhance Blunt Weapon
	[2955] = 34340, -- Weight Weapon
	[3093] = 37360, -- Consecrated Weapon
	[3102] = 38615, -- Poison
	[3265] = 45395, -- Blessed Weapon Coating
	[3266] = 45397, -- Righteous Weapon Coating
	[3298] = 47904, -- Exceptional Mana Oil
	[3592] = 28898, -- Blessed Wizard Oil
	[3593] = 28891, -- Consecrated Weapon
	[3868] = 64401, -- Glow Worm
	[4225] = 95244, -- Heat-Treated Spinning Lure
	[4264] = 98849, -- Glass Fishing Bobber
	[4891] = 125164, -- Ancient Pandaren Fishing Lure
	[4919] = 128587, -- Fishing Hat Lure
	[5386] = 174471, -- Worm Supreme
	[5400] = 334294, -- Flametongue Weapon
	[5401] = 334302, -- Windfury Weapon
	[6188] = 320798, -- Shadowcore Oil
	[6190] = 321389, -- Embalmer's Oil
	[6198] = 322749, -- Sharpen Weapon
	[6199] = 322761, -- Weight Weapon
	[6200] = 322762, -- Sharpen Weapon
	[6201] = 322763, -- Weight Weapon
	[6224] = 324064, -- Apply Armor Kit
	[6225] = 324068, -- Apply Armor Kit
	[6252] = 334456, -- Searing Armor
}

local function onEnter(self)
	GameTooltip:SetOwner(self, 'ANCHOR_BOTTOMLEFT')

	if self:GetAttribute('index') then
		local unit = self:GetParent():GetAttribute('unit')
		GameTooltip:SetUnitAura(unit, self:GetID(), 'HELPFUL')
		GameTooltip:Show()
	else
		GameTooltip:AddSpellByID(self.enchantSpellID)
		GameTooltip:AddLine(' ')
		GameTooltip:AddLine(addon:FormatShortTime(self.expiration) .. ' remaining')
		GameTooltip:Show() -- render
	end
end

local function updateAura(self, index)
	local unit = self:GetParent():GetAttribute('unit')

	local exists, texture, count, _, _, expiration = UnitAura(unit, index, 'HELPFUL')
	if exists then
		self.icon:SetTexture(texture)
		self.count:SetValue(count)
		self.expiration = expiration - GetTime()
	end
end

local function updateEnchant(self, slotID)
	local enchanted, duration, count, enchantID, _
	if slotID == 16 then -- main hand
		enchanted, duration, count, enchantID = GetWeaponEnchantInfo()
	elseif slotID == 17 then -- off hand
		_, _, _, _, enchanted, duration, count, enchantID = GetWeaponEnchantInfo()
	end

	if enchanted then
		self.enchantSpellID = ENCHANT_IDS[enchantID]

		self.icon:SetTexture(GetSpellTexture(self.enchantSpellID))
		self.count:SetValue(count)
		self.expiration = duration / 1000
	end
end

local function onAttributeChanged(self, attribute, value)
	if attribute == 'index' then
		updateAura(self, value)
	elseif attribute == 'target-slot' then
		updateEnchant(self, value)
	end
end

local buffs = addon:CreateFrame('Buffs', UIParent, 'SecureAuraHeaderTemplate')
buffs:SetPoint('TOPRIGHT', Minimap, 'TOPLEFT', -20, 0)
buffs:SetAttribute('initialConfigFunction', [[
	self:SetAttribute('type2', 'cancelaura')
	self:SetWidth(26)
	self:SetHeight(26)
]])

for attribute, value in next, {
	template = 'SecureActionButtonTemplate',
	unit = 'player',
	filter = 'helpful',

	-- style
	sortMethod = 'TIME',
	sortDirection = '+',
	point = 'TOPRIGHT',
	minWidth = 330,
	minHeight = 99,
	xOffset = -33,
	wrapYOffset = -33,
	wrapAfter = 15,

	-- temporary enchants
	includeWeapons = 1,
	weaponTemplate = 'SecureActionButtonTemplate'
} do
	buffs:SetAttribute(attribute, value)
end

buffs:HookScript('OnAttributeChanged', function(self, attribute, child)
	if not (attribute:match('^frameref%-child') or attribute:match('^tempenchant')) then
		return
	end

	if type(child) == 'userdata' then
		child = GetFrameHandleFrame(child)
	end

	child:SetScript('OnEnter', onEnter)
	child:SetScript('OnLeave', GameTooltip_Hide)
	addon:CreateAura(child)

	child:RegisterForClicks('RightButtonUp')
	child:SetScript('OnAttributeChanged', onAttributeChanged)

	if attribute:match('^tempenchant') then
		child:SetBackdropBorderColor(0.6, 0, 1)

		-- we'll need to override the OnEnter script handler
		child:SetScript('OnEnter', onEnter)
	end
end)

buffs:Show() -- no clue why it's hidden by default

-- show vehicle buffs
RegisterAttributeDriver(buffs, 'unit', '[vehicleui] vehicle; player')

-- hide blizzard auras
addon:Hide(TemporaryEnchantFrame)
addon:Hide(BuffFrame)
