-- generated by scripts/get_hearthstone_ids.py
local _, addon = ...
addon.HEARTHSTONE_IDS = {
	name = 'Hearthstone',

	{'toy', 54452}, -- Ethereal Portal
	{'toy', 64488}, -- The Innkeeper's Daughter
	{'toy', 93672}, -- Dark Portal
	{'toy', 142542}, -- Tome of Town Portal
	{'toy', 162973}, -- Greatfather Winter's Hearthstone
	{'toy', 163045}, -- Headless Horseman's Hearthstone
	{'toy', 163206}, -- Weary Spirit Binding
	{'toy', 165669}, -- Lunar Elder's Hearthstone
	{'toy', 165670}, -- Peddlefeet's Lovely Hearthstone
	{'toy', 165802}, -- Noble Gardener's Hearthstone
	{'toy', 166746}, -- Fire Eater's Hearthstone
	{'toy', 166747}, -- Brewfest Reveler's Hearthstone
	{'toy', 168907}, -- Holographic Digitalization Hearthstone
	{'toy', 172179}, -- Eternal Traveler's Hearthstone
	{'toy', 180290, show='[covenant:nightfae]'}, -- Night Fae Hearthstone
	{'toy', 182773, show='[covenant:necrolord]'}, -- Necrolord Hearthstone
	{'toy', 183716, show='[covenant:venthyr]'}, -- Venthyr Sinstone
	{'toy', 184353, show='[covenant:kyrian]'}, -- Kyrian Hearthstone
	{'toy', 188952}, -- Dominated Hearthstone
	{'toy', 190196}, -- Enlightened Hearthstone
	{'toy', 190237}, -- Broker Translocation Matrix
	{'toy', 193588}, -- Timewalker's Hearthstone
	{'toy', 200630}, -- Ohn'ir Windsage's Hearthstone
	{'toy', 206195}, -- Path of the Naaru
	{'toy', 209035}, -- Hearthstone of the Flame
	{'item', 6948}, -- Hearthstone
}
