name: Lint

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          annotate: warning
          args: --no-color
